# This is a GitHub Action workflow to generate HTML file and deploy it with GitHub Pages

name: gh-pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  gh-pages:
    # This workflow contains a job to build HTML documents and deploy it with GitHub Pages
    if: github.event.push.commits[0][author][name] != "github-actions"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install Node.JS
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Using latest LTS
      
      # Install Dependencies
      - name: Install Dependencies
        run: npm ci
        env:
          CI: true 
      
      # Build github pages
      - name: Build GitHub Pages
        run: npm run build-html
        env:
          CI: true
      
      # Commit
      # TODO
